### ISSUE TITLE
Port vex to Urho3D game engine, it is possible?

### ISSUE THREAD

**Issue by aster2013** [AlwaysGeeky/Vox#193]
[Urho3D](https://github.com/urho3d/Urho3D) is a free lightweight, cross-platform 2D and 3D game engine implemented in C++ and released under the MIT license.

If you port Vox to Urho3D game engine, it can run on Windows, Linux, Mac OS, iOS, Android ... platforms. Urho3D do a lots of things for you, and you can focus on the Vox game.

**Comment by AlwaysGeeky** [comment]
I don't think this is something I will be actively pursuing, but feel free to look into this yourself, there is no restriction on trying to port this over.
