### ISSUE TITLE
Weapon trails are not frame rate independent.

### ISSUE THREAD

**Issue by AlwaysGeeky** [AlwaysGeeky/Vox#2]
Depending on FPS, weapon trail rendering can be rendered incorrectly, or different when the FPS is different.

**Comment by giawa** [comment]
You may find this issue is fixed with commit 319c2600737be7650c9deac40739acb60a8905f9 as weapon trails are updated with m_deltaTime.

**Comment by AlwaysGeeky** [comment]
Hmmmm I will investigate. I just noticed previously that depending on the frame rate that weapon trails didnt always seem to be the same length... i.e sometimes the trail was longer and other times it was really short. I guessed this was to do with how I was updating the weapon trail update() call and the timing within it.

Thanks for the heads up.

**Comment by AlwaysGeeky** [comment]
Fixed in commit 989b20ba825b715782db2a158f9d4d20093aabe1

Basically re-wrote the weapon trails updating and rendering so not to use a static index and instead allow weapon trails to have a 'trail-time' in the weapon config file.
