### ISSUE TITLE
Cubby engine based on your Vox engine

### ISSUE THREAD

**Issue by utilForever** [AlwaysGeeky/Vox#203]
I opened Cubby engine based on your Vox engine (GNU GPL v3).
(http://www.github.com/MineScroll/Cubby).
Thank you and thanks for your source code.
Please don't hesitate to contact me if you have any further questions.

**Comment by AlwaysGeeky** [comment]
Hey man, I noticed. No worries, glad my source and engine can be of help to you.

I will watch your project and see how it progresses :)

Let me know if you need any further assistance or if there is anything I can help with.

Cheers.

**Comment by utilForever** [comment]
I have a problem related to rendering as below. I saw something like walls separate the world. Why it is happen?
![capture](https://cloud.githubusercontent.com/assets/5622661/18351457/35406cbe-7615-11e6-953f-7f855228b303.PNG)

**Comment by AlwaysGeeky** [comment]
Is this a physical wall, or just a rendering issue? Can you pass by the wall and move through it?

**Comment by utilForever** [comment]
The latter. I can pass by the wall.

**Comment by utilForever** [comment]
I found why it is happen. I'll fix it tonight. Thanks.

**Comment by AlwaysGeeky** [comment]
Great, please let me know what the cause and resolution for the issue was and I can see if this is something affecting the Vox main code base.

:)
