### ISSUE TITLE
Questions about Vox Engine

### ISSUE THREAD

**Issue by utilForever** [AlwaysGeeky/Vox#28]
Hello, my name is Chris. Your project "Vox" is amazing and fantastic!
I am trying to make MMORPG named "MineScroll".
I have plan to publish Steam Greenlight when it completed.
So, I have two questions.
1. Can I make new engine based on "Vox"? (I want to make Modern C++ based engine).
2. Can I see the class diagram of "Vox" as much as possible, if you could do that?
Thank you for your hard work! :D

**Comment by AlwaysGeeky** [comment]
Hi utilForever,

Thank you for your kind words.

1) Yes you are able to use the Vox engine as you wish, however please see the licence information on this github repo for usage terms.

2) I can't provide you with any additional documentation or class diagrams, unfortunately you will have to do the best you can with the source that is provided here. In the future I may add additional documentation outside of the source code but right now I have no plans to do this in the immediate future.

Thanks!

**Comment by utilForever** [comment]
@AlwaysGeeky 
Hi Steve,

Thanks for your response.

I know that the licence of this repo is GNU GPL.
Please advise me on some dos and don'ts.

Thanks!

**Comment by AlwaysGeeky** [comment]
You can find a good summary of the GNU GPL here: http://choosealicense.com/licenses/gpl-3.0/

**Comment by utilForever** [comment]
Thx. :D
