### ISSUE TITLE
MS3DAnimator.cpp error

### ISSUE THREAD

**Issue by darkfighter852** [AlwaysGeeky/Vox#32]
when i try to compile on win 7, debug build the project found in linux whit CodeBlocks, i get 
\\\\Vox-master\Vox-master\source\models\MS3DAnimator.cpp|262|error: '_strcmpi' was not declared in this scope|

**Comment by AlwaysGeeky** [comment]
Ok, I haven't tried to compile using codeblocks on windows, The codeblocks project is mostly for linux... are you able to try to compile with Visual Studio on windows?

**Comment by darkfighter852** [comment]
yes, the vs2015 project runs fine, thank you
