### ISSUE TITLE
Segmentation fault in renderer.cpp

### ISSUE THREAD

**Issue by WillManse** [AlwaysGeeky/Vox#35]
Ubuntu Wily.
Running debug in Code::Blocks
Line 2113.

VertexArray *pVertexArray = m_vertexArrays[pMesh->m_staticMeshId];

m_staticMeshId is sometimes out of bounds.

**Comment by AlwaysGeeky** [comment]
Thanks for reporting this, I actually know about this and will look to fix this soon. It is a threading issue with the rendering and the chunk loading.

Now that this is an official issue it will force me to work on it, cheers!
