### ISSUE TITLE
small update

### ISSUE THREAD

**Issue by darkfighter852** [AlwaysGeeky/Vox#40]
i dont know if u seen this so i tought to make a issue, i "ruined" my github and everything is messed-up right now

i got some compile warnings, i tought it might help you

https://github.com/darkfighter852/Vox/commit/e9ca16ed65d641afddb64e6f741ec12e3be465d6

and use size_t insead of int in for loops. it works better.

https://github.com/darkfighter852/Vox/commit/179b7ebf439608adb87ebbf695eecd3930eae5ca

also i messed around whit <thread> but dont mind that, im still learning
anyway take a look and tell me what you think.

**Comment by AlwaysGeeky** [comment]
Hi,

I saw the compile warnings you reported and will look into fixing these.

For the changing of ints to size_t in loops, this really wont have much performance changes, could you explain how this works better for you?

Thanks.

**Comment by darkfighter852** [comment]
well i run the VisualStudio profiler tool, and it shows it runs faster by 2%-4% when size_t, i read somewere that its better to use size_t on for loops if u build on x64 because int may be 32bit one, but size_t will make sure its 64bit one and unsigned (not like for loops are going down) and by beeing 64bit ints it will make the processor go faster through the loops. anyway i dont have the links but i think i read somewere on stackoverflow. hope this helps
